## Import the libraries

In [18]:
import os
import sys

import matplotlib.pyplot as plt
import pandas as pd


PROJECT_PATH = '../'
print(PROJECT_PATH)

sys.path.append(PROJECT_PATH)

from nima.utils.image_utils import get_images
from nima.evaluate.evaluate_model import eval_technical_model, eval_aesthetic_model
from nima.utils.preprocess import show_images_with_score, get_mean_quality_score, normalize_ratings

../

# Technical Score

In [13]:
# Initialize values
tech_weight_file = os.path.join(PROJECT_PATH, 'weights', 'technical', 'weights-mobilenetv2-technical.hdf5')
# tech_weight_file = os.path.join(PROJECT_PATH, 'weights', 'technical', 'MobileNetV2_technical_pretrain.hdf5')
# tech_weight_file = os.path.join(PROJECT_PATH, 'weights', 'technical', 'weights_mobilenet_technical.hdf5')

In [16]:
pearsonr, spearmanr, df_test = eval_technical_model(p_model_name='mobilenet_v2', p_weight_file=tech_weight_file)
print(f"Pearson score : {pearsonr}, Spearman score : {spearmanr}")

Images directory C:\Users\amaindola\github\img-quality-assesment\data\tid2013\distorted_images
Evaluating Model...
	Base CNN module - tensorflow.keras.applications.mobilenet_v2.MobileNetV2
	Loading weights ../weights\technical\weights-mobilenetv2-technical.hdf5
	Model compiled successfully.
	Found 300 valid image filenames belonging to 1 classes.
	Testing with Batch size:32
10/10 [==============================] - 9s 679ms/step - loss: 11.3212 - pearson_correlation: 0.0000e+00 - mean_abs_percentage: -inf
	loss(mse) : 11.32123851776123 | accuracy([<function pearson_correlation at 0x0000027D11EEA5E0>, <function mean_abs_percentage at 0x0000027D1386E310>]) : [0.0, -inf]
	saving predictions to C:\Users\amaindola\github\img-quality-assesment\results\MobileNetV2_technical_eval_pred.csv
Pearson score : 0.3398644105485628, Spearman score : 0.2450280698352486

In [17]:
df_test

     image_id     mean      std  pred_mean
0    i10_06_5  3.40541  0.11756   3.761403
1    i19_02_4  5.00000  0.11467   3.601012
2    i19_22_5  2.75676  0.12329   2.699538
3    i25_22_4  3.40000  0.12905   3.276627
4    I09_01_1  5.36364  0.16497   3.330522
..        ...      ...      ...        ...
295  i23_09_3  5.70588  0.14723   3.695766
296  i05_22_2  5.25000  0.14895   3.389492
297  i03_21_4  3.17949  0.08004   3.731812
298  i06_16_2  6.25000  0.15404   3.313792
299  i14_10_4  3.05556  0.11072   3.467660

[300 rows x 4 columns]

# Aesthetic score

In [48]:
# aes_weight_file = os.path.join(PROJECT_PATH, 'weights', 'aesthetic', 'MobileNet_aesthetic.hdf5')

In [50]:
aes_weight_file = os.path.join(PROJECT_PATH, 'weights', 'aesthetic', 'MobileNetV2_aesthetic.hdf5')
df_test = eval_aesthetic_model(p_model_name='mobilenet_v2', p_weight_file=aes_weight_file)
df_test

Images directory C:\Users\amaindola\github\img-quality-assesment\data\ava\images
Evaluating Model...
aesthetic
	Base CNN module - tensorflow.keras.applications.mobilenet_v2.MobileNetV2
	Model compiled successfully.
	Found 300 valid image filenames belonging to 10 classes.
	Testing with Batch size:32
10/10 [==============================] - 7s 526ms/step - loss: nan - two_class_quality: 0.3854 - mean_abs_percentage_ava: nan
	loss(<function earth_movers_distance at 0x0000027D119E1940>) : nan | accuracy([<function two_class_quality at 0x0000027D1386E280>, <function mean_abs_percentage_ava at 0x0000027D1386E3A0>]) : [0.3854166865348816, nan]
(300, 10)
	spearman_correlation : 0.48370040225096983, pearson_correlation : 0.4747253213859996 Earth Movers Distance : 17.185679750303816 Two class Quality : 0.7133333333333334 Mean Absolute Percentage : 0.8920718160503202

    image_id  mean_score  pred_mean_score
0      60850       5.049            4.574
1      16288       5.005            5.147
2      76352       3.880            4.658
3     118559       5.231            5.374
4      13186       3.532            5.134
..       ...         ...              ...
295   101915       4.241            5.434
296   132524       4.857            4.760
297    28258       5.369            4.782
298   136687       5.768            5.506
299    24454       6.370            5.711

[300 rows x 3 columns]

In [51]:
aes_weight_file = os.path.join(PROJECT_PATH, 'weights', 'aesthetic', 'MobileNetV2_aesthetic_best.hdf5')
df_test = eval_aesthetic_model(p_model_name='mobilenet_v2', p_weight_file=aes_weight_file)
df_test

Images directory C:\Users\amaindola\github\img-quality-assesment\data\ava\images
Evaluating Model...
aesthetic
	Base CNN module - tensorflow.keras.applications.mobilenet_v2.MobileNetV2
	Model compiled successfully.
	Found 300 valid image filenames belonging to 10 classes.
	Testing with Batch size:32
10/10 [==============================] - 8s 579ms/step - loss: nan - two_class_quality: 0.5021 - mean_abs_percentage_ava: nan
	loss(<function earth_movers_distance at 0x0000027D119E1940>) : nan | accuracy([<function two_class_quality at 0x0000027D1386E280>, <function mean_abs_percentage_ava at 0x0000027D1386E3A0>]) : [0.5020833611488342, nan]
(300, 10)
	spearman_correlation : 0.6349041178999948, pearson_correlation : 0.674826695910684 Earth Movers Distance : 65.29433922086963 Two class Quality : 0.6166666666666667 Mean Absolute Percentage : 0.8941226402017469

    image_id  mean_score  pred_mean_score
0     100835       5.221            4.960
1      67478       4.129            5.412
2      14445       5.571            4.476
3      58363       5.349            4.896
4     124292       5.726            4.708
..       ...         ...              ...
295    30565       5.526            5.201
296    89850       2.857            3.504
297   140975       5.616            4.692
298    50737       6.493            6.126
299    53031       4.885            5.039

[300 rows x 3 columns]